stages:
  - build
  - test
build:
  stage: build
  image: openjdk:12-alpine
  script:
    - ./gradlew build
  artifacts:
    paths:
      - ./build/libs/

smoke_test:
  stage: test
  image: openjdk:12-alpine
  before_script:
    - apk --no-cache add curl
    - apk --no-cache add tree
  script:
    - java -jar ./build/libs/cars-api.jar
    - sleep 30
    - curl http://localhost:5000/actuator/health | grep "UP"