variables:
  ARTIFACT_NAME: cars-api-v$CI_PIPELINE_IID.jar

stages:
  - build
  - test
  - deploy
build:
  stage: build
  image: openjdk:12-alpine
  script:
    - ./gradlew build
    - mv ./build/libs/cars-api.jar ./build/libs/$ARTIFACT_NAME
  artifacts:
    paths:
      - ./build/libs/

smoke_test:
  stage: test
  image: openjdk:12-alpine
  before_script:
    - apk --no-cache add curl
  script:
    - java -jar ./build/libs/$ARTIFACT_NAME &
    - sleep 30
    - curl http://localhost:5000/actuator/health | grep "UP"

deploy:
  stage: deploy
  image:
    name: banst/awscli
    entrypoint: [""]
  script:
    - aws configure set region sa-east-1
    - aws s3 cp ./build/libs/$ARTIFACT_NAME s3://unique-cars-api-deployment/$ARTIFACT_NAME